/**
 * API 에러 코드 상수 (엔드포인트 명세 기반)
 * HTTP status 와 별개로 프로젝트 전용 코드를 사용한다.
 */
export const API_CODE = {
  SUCCESS: 700,
  CREATED: 701,
  EMPTY_RESULT: 704,
  VALIDATION_ERROR: 900,
  AUTH_FAILED: 901,
  NOT_FOUND: 904,
  CONFLICT: 909,
}

export const ERROR_CODE = {
  // Auth
  LOGIN_FAILED: 'LOGIN_FAILED',
  INVALID_LOGIN_REQUEST: 'INVALID_LOGIN_REQUEST',
  INVALID_SIGNUP_REQUEST: 'INVALID_SIGNUP_REQUEST',
  DUPLICATE_USER_NAME: 'DUPLICATE_USER_NAME',
  USERNAME_REQUIRED: 'USERNAME_REQUIRED',
  INVALID_USERNAME_FORMAT: 'INVALID_USERNAME_FORMAT',
  REFRESH_TOKEN_REQUIRED: 'REFRESH_TOKEN_REQUIRED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  EXPIRED_REFRESH_TOKEN: 'EXPIRED_REFRESH_TOKEN',
  REFRESH_TOKEN_MISMATCH: 'REFRESH_TOKEN_MISMATCH',

  // Attraction
  ATTRACTION_NOT_FOUND: 'ATTRACTION_NOT_FOUND',

  // Schedule
  SCHEDULE_NOT_FOUND: 'SCHEDULE_NOT_FOUND',
  INVALID_TRIP_DATE: 'INVALID_TRIP_DATE',
  INVALID_BUDGET: 'INVALID_BUDGET',
  INVALID_PEOPLE_COUNT: 'INVALID_PEOPLE_COUNT',

  // Node
  NODE_NOT_FOUND: 'NODE_NOT_FOUND',

  // Edge
  EDGE_NOT_FOUND: 'EDGE_NOT_FOUND',
}
